name: Acceptance Pipeline

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  acceptance:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.4'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

    - name: Generate Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Acceptance Tests
      env:
        APP_ENV: acceptance
        APP_DEBUG: false
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        php artisan migrate:fresh --force
        php artisan test --testsuite=Acceptance
