name: Laravel

on:
  push:
  pull_request:
            - name: Laravel Pint
  # You may pin to the exact commit or the version.
  # uses: aglipanci/laravel-pint-action@8eedec46a1856977c41667f9c66d5562fa3f9c08
  uses: aglipanci/laravel-pint-action@2.4
  with:
    # would you like to run Pint on test mode
    testMode: # optional
    # would you like to run Pint on verbose mode
    verboseMode: # optional
    # specify the custom config path
    configPath: # optional
    # pint preset
    preset: # optional
    # only format changed files
    onlyDirty: # optional
    # laravel/pint composer version to install a specific version.
    pintVersion: # optional
    # Use Laravel Pint version from project composer lock file. Lock file must be preset to use this flag.
    useComposer: # optional
          
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.4'

    - uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Migrations
      run: php artisan migrate:fresh --force
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --no-coverage
